In [2]:
# Solution 1
import numpy as np
a=np.arange(2,51,3)
print(a)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [2]:
# Solution 2
import numpy as np
L1=[]
L2=[]
for i in range(5):
    x=int(input("values in L1 "))
    L1.append(x)
for i in range(5):
    y=int(input("values in L2 "))
    L2.append(y)
print(L1)
print(L2)
arr1=np.array(L1)
arr2=np.array(L2)
print(arr1)
print(arr2)
concat_arr=np.concatenate((arr1,arr2))
print("Concatenatd array:",concat_arr)
sort_arr=np.sort(concat_arr)
print("Sorted array:",sort_arr)

values in L1 23
values in L1 56
values in L1 78
values in L1 51
values in L1 98
values in L2 77
values in L2 34
values in L2 49
values in L2 21
values in L2 64
[23, 56, 78, 51, 98]
[77, 34, 49, 21, 64]
[23 56 78 51 98]
[77 34 49 21 64]
Concatenatd array: [23 56 78 51 98 77 34 49 21 64]
Sorted array: [21 23 34 49 51 56 64 77 78 98]


In [6]:
# Solution 3
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("No. of dimensions:",arr.ndim)
print("Size of array:",arr.size)

No. of dimensions: 2
Size of array: 6


In [2]:
# Solution 4
import numpy as np
arr=np.arange(10)
print(arr)
print("Shape of 1D array:",arr.shape)
new_arr=np.expand_dims(arr,axis=1)
print(new_arr)
print("Shape of 2D array:",new_arr.shape)

[0 1 2 3 4 5 6 7 8 9]
Shape of 1D array: (10,)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Shape of 2D array: (10, 1)


In [16]:
# Solution 5
import numpy as np
arr1=np.matrix([[1,2,3],[4,5,6]])
arr2=np.matrix([[7,8,9],[10,11,12]])
print("Horizontal stacking:",np.hstack((arr1,arr2)))
print("Vertical stacking:",np.vstack((arr1,arr2)))

Horizontal stacking: [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Vertical stacking: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
# Solution 6
import numpy as np
arr=np.array([1,4,5,7,3,5,4,8,7,6,1,2])
unique,counts=np.unique(arr,return_counts=True)
new_arr=np.asarray((unique,counts)).T
print(new_arr)


[[1 2]
 [2 1]
 [3 1]
 [4 2]
 [5 2]
 [6 1]
 [7 2]
 [8 1]]
